package uk.co.hsim.assetaudit.importfile;

public enum ImportIssueCode {
    FILE_UNSUPPORTED_TYPE,
    FILE_OPEN_FAILED,
    HEADER_ROW_NOT_FOUND,
    REQUIRED_COLUMN_MISSING,
    DUPLICATE_COLUMN,
    ROW_EMPTY,
    ASSET_TAG_BLANK,
    ASSET_TAG_DUPLICATE,
    ASSET_TAG_TOO_LONG,
    DEPARTMENT_BLANK,
    DESCRIPTION_BLANK,
    STATUS_BLANK,
    SITE_BLANK,
    LOCATION_BLANK,
    CATEGORY_BLANK,
    SUB_CATEGORY_BLANK,
    BRAND_BLANK,
    MODEL_BLANK,
    PRIMARY_USER_BLANK,
    OWNER_BLANK,
    PRIOR_AUDIT_DETAILS_PRESENT,
    UNKNOWN_STATUS,
    MALFORMED_ROW,
    IMPORT_TRANSACTION_FAILED
}
